from app.config import settings
from app.providers.base import ModelProvider, ProviderSegment


class HuggingFaceProvider(ModelProvider):
    name = "huggingface"

    def health(self) -> dict:
        # Placeholder until concrete model/runtime is selected.
        return {
            "provider": self.name,
            "status": "ok" if not settings.hf_offline else "degraded",
            "offline_mode": settings.hf_offline,
            "message": "HF provider skeleton enabled; runtime/model binding pending.",
        }

    def transcribe(self, video_object_key: str, options: dict | None = None) -> list[ProviderSegment]:
        model_label = "hf-model"
        if options and isinstance(options.get("model_id"), str):
            model_label = options["model_id"]

        base_texts = [
            f"[{model_label}] Welcome. This transcript is generated by the HF provider skeleton.",
            "Segment timing and confidence are mocked until the production model is wired in.",
            "This path is intended for future Hugging Face weights and runtime integration.",
        ]

        segments: list[ProviderSegment] = []
        cursor = 0.0
        for idx, line in enumerate(base_texts):
            duration = 4.0
            segments.append(
                ProviderSegment(
                    order_index=idx,
                    start_sec=round(cursor, 3),
                    end_sec=round(cursor + duration, 3),
                    text=line,
                    confidence=0.76 - (idx * 0.03),
                )
            )
            cursor += duration
        return segments

    def regenerate(self, segments: list[ProviderSegment], options: dict | None = None) -> list[ProviderSegment]:
        return [
            ProviderSegment(
                order_index=segment.order_index,
                start_sec=segment.start_sec,
                end_sec=segment.end_sec,
                text=f"{segment.text} [hf-pass]",
                confidence=max(segment.confidence - 0.02, 0.5),
            )
            for segment in segments
        ]
